// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Open a new CozoDB database.
///
/// - `engine`: "mem" for in-memory, "sqlite" for persistent SQLite
/// - `path`: file path for sqlite engine, empty string for mem
/// - `options`: JSON string of engine options, use "{}" for defaults
///
/// Returns an opaque CozoDb handle.
CozoDb cozoOpenDb({
  required String engine,
  required String path,
  required String options,
}) => RustLib.instance.api.crateApiSimpleCozoOpenDb(
  engine: engine,
  path: path,
  options: options,
);

/// Run a CozoScript query.
///
/// - `db`: the database handle
/// - `script`: CozoScript query string
/// - `params_json`: JSON object of named parameters, e.g. '{"name": "Alice"}'
/// - `immutable`: if true, the query is run in read-only mode
///
/// Returns a JSON string with the query result.
Future<String> cozoRunQuery({
  required CozoDb db,
  required String script,
  required String paramsJson,
  required bool immutable,
}) => RustLib.instance.api.crateApiSimpleCozoRunQuery(
  db: db,
  script: script,
  paramsJson: paramsJson,
  immutable: immutable,
);

/// Export relations from the database.
///
/// - `relations_json`: JSON array of relation names, e.g. '["users", "edges"]'
///
/// Returns JSON string with exported data.
Future<String> cozoExportRelations({
  required CozoDb db,
  required String relationsJson,
}) => RustLib.instance.api.crateApiSimpleCozoExportRelations(
  db: db,
  relationsJson: relationsJson,
);

/// Import relations into the database.
///
/// - `data_json`: JSON string in the same format as export output.
Future<void> cozoImportRelations({
  required CozoDb db,
  required String dataJson,
}) => RustLib.instance.api.crateApiSimpleCozoImportRelations(
  db: db,
  dataJson: dataJson,
);

/// Backup the database to a file path.
Future<void> cozoBackup({required CozoDb db, required String path}) =>
    RustLib.instance.api.crateApiSimpleCozoBackup(db: db, path: path);

/// Restore the database from a backup file.
Future<void> cozoRestore({required CozoDb db, required String path}) =>
    RustLib.instance.api.crateApiSimpleCozoRestore(db: db, path: path);

/// Import relations from a backup file without fully restoring.
Future<void> cozoImportFromBackup({
  required CozoDb db,
  required String path,
  required String relationsJson,
}) => RustLib.instance.api.crateApiSimpleCozoImportFromBackup(
  db: db,
  path: path,
  relationsJson: relationsJson,
);

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<CozoDb>>
abstract class CozoDb implements RustOpaqueInterface {}
